import React from 'react';

export const metadata = {
  title: "StatsPage || BondKeeper",
  description: "Generated by create next app",
};

const StatsPage = () => {
    return (
        <div>
            this is stats
        </div>
    );
};

export default StatsPage;