import React from 'react';

export const metadata = {
  title: "TimelinePage || BondKeeper",
  description: "Generated by create next app",
};

const TimeLinePage = () => {
    return (
        <div>
            <h2>this is timeline</h2>
        </div>
    );
};

export default TimeLinePage;