import React from 'react';

export const metadata = {
  title: "HomePage || BondKeeper",
  description: "Generated by create next app",
};


const HomePage = () => {
    return (
        <div>
            <h2>this is home</h2>
        </div>
    );
};

export default HomePage;